[project]
name = 'cobra-exercises'
version = '0.1.0.dev1'
description = 'A meta package for Cobra exercises.'
readme = 'README.md'
authors = [ { name = 'IS4S', email = 'pntos@is4s.com' } ]
requires-python = '>=3.10'
license = 'Apache-2.0'
license-files = [ 'LICENSE' ]

classifiers = [
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
]

dependencies = [
    'navanalysis-lcm==0.1.5',
    "pntos-api>=2.0.0,<3.0.0",
    'pntos-cobra==2.1.0-0.dev4',
    'pntos-python-datasets-lcm==0.1.0',
]

[dependency-groups]
dev = [
    'mypy==1.18.2',
    'myst-parser>=4',
    'pip>=24',
    # cobra-exercises branch, committed 9 September 2026
    'cobra-exercises-docs-data @ git+https://git@github.com/Open-PNT/navigation-data.git@4668e34e5aa6fb42e521bf1515191ed294cb9a43',
    'pytest>=8.2',
    'ruff==0.13.2',
    'sphinx>=7.3.7',
    'sphinx-design',
    'sphinx-rtd-theme>=3.0.2',
]

[tool.ruff]
format.quote-style = 'single'

[tool.mypy]
strict = true
disable_error_code = [ 'import-untyped', 'no-untyped-call' ]
warn_unreachable = true

[tool.uv]
package = false
