name: Check

on: [push, pull_request]

jobs:
    ruff-check:
        name: ruff check
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup

        - name: Run ruff check
          run: docker exec pntos-python ruff check

    ruff-format:
        name: ruff format
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup

        - name: Run ruff format
          run: docker exec pntos-python ruff format --diff

    exercise-synchronization:
        name: Exercise synchronization
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup

        - name: Run app sync check
          run: |
            set -xe
            docker exec pntos-python git config --global --add safe.directory /work
            docker exec pntos-python util/check_sync.sh

    Requirements-up-to-date:
        name: Requirements up-to-date
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup

        - name: Check requirements files
          run: |
            set -xe
            # Generate requirements*.txt files
            docker exec pntos-python uv export --frozen --no-dev --no-hashes -o requirements-minimal.txt
            docker exec pntos-python uv export --frozen --no-hashes -o requirements.txt
            # If there's still a diff, then there's unsynced changes; fail the job.
            git diff --exit-code

    mypy:
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup

        - name: Run tests
          run: |
            set -xe
            docker exec pntos-python mypy exercises/
            docker exec pntos-python mypy .details/

    documentation-check:
        name: Documentation check
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup

        - name: Build docs
          run: docker exec -e TZ=UTC pntos-python util/build_docs.sh

        # On non-main pushes, archive the docs.
        - name: Archive Docs
          if: github.ref != 'refs/heads/main'
          uses: actions/upload-artifact@v4
          with:
            name: documentation
            path: docs/build

        # On main pushes, upload for deployment
        - name: Upload Pages Artifact
          if: github.ref == 'refs/heads/main'
          uses: actions/upload-pages-artifact@v3
          with:
            path: docs/build

    link-check:
        name: Check external links
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup

        - name: Build docs with external link check
          run: docker exec -e TZ=UTC pntos-python sphinx-build -b linkcheck --exception-on-warning docs/ docs/build/

    exercise-apps:
        name: Run ${{ matrix.app }}
        runs-on: ubuntu-24.04
        strategy:
          fail-fast: false
          matrix:
            app:
              - test_pos_baro_stub
              - test_pos_baro_sol
              - test_zupt_stub
              - test_zupt_sol
              - test_direction_sol
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup

        - name: Run app
          run: docker exec pntos-python pytest test -k ${{ matrix.app }} -s

    pip-workflow:
        name: Test ${{ matrix.requirements }} pip workflow
        runs-on: ubuntu-24.04
        strategy:
          fail-fast: false
          matrix:
            requirements:
              - requirements.txt
              - requirements-minimal.txt
        steps:
        - uses: actions/checkout@v4

        - name: Set up
          uses: ./.github/actions/setup
          with:
            sync: false

        - name: Restore pip cache
          uses: actions/cache/restore@v4
          with:
            path: ~/.cache
            key: pip-cache-${{ matrix.requirements }}-${{ hashFiles(matrix.requirements) }}
            restore-keys: pip-cache-${{ matrix.requirements }}

        - name: Install Python packages
          run: |
            set -xe
            docker exec pntos-python python3 -m venv /work/.venv
            docker exec pntos-python .venv/bin/pip install -v -r ${{ matrix.requirements }}

        - name: Save pip cache
          uses: actions/cache/save@v4
          with:
            path: ~/.cache
            key: pip-cache-${{ matrix.requirements }}-${{ hashFiles(matrix.requirements) }}

        - name: Run an app
          run: docker exec pntos-python postprocessing/run_app_and_record_data.py exercises/new_app_exercise/pos_baro_app.py

    Copyright:
        name: Copyright year
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Check copyright year
          run: (! grep --color -i "copyright.*$(( $(date +%Y) - 1 ))" $(git ls-files))

    deploy-docs:
        if: github.ref == 'refs/heads/main'
        needs: documentation-check
        runs-on: ubuntu-24.04
        permissions:
          pages: write
          id-token: write
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        steps:
        - name: Deploy Documentation
          id: deployment
          uses: actions/deploy-pages@v4
